language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install expat libexpat1-dev 
  
before_script:  
  - mkdir -p $HOME/overpass
  - pushd src/
  - chmod u+x test-bin/*.sh
  - autoscan
  - aclocal
  - autoheader
  - libtoolize
  - automake --add-missing
  - autoconf
  - popd
  - mkdir -p build
  - cd build
  - ../src/configure CXXFLAGS="-O3" --prefix=$EXEC_DIR

script:  
  - make install
  - cp -R test-bin/ bin/ cgi-bin/ ../src
  - export PATH=$PATH:$HOME/overpass/bin:$HOME/overpass/cgi-bin:$HOME/overpass/test-bin  
  - cd ../osm-3s_testing/
  - ../src/test-bin/run_testsuite.sh 40

branches:
  only:
    - travis_test

os:
  - linux
  
env:
  - EXEC_DIR=$HOME/overpass

