language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install expat libexpat1-dev 
  
before_script:  
  - mkdir -p $HOME/bin
  - pushd src/
  - autoscan
  - aclocal
  - autoheader
  - libtoolize
  - automake --add-missing
  - autoconf
  - popd
  - mkdir -p build
  - cd build
  - ../src/configure CXXFLAGS="-O3" --prefix=$EXEC_DIR

script:  
  - make

branches:
  only:
    - travis_test

os:
  - linux
  
env:
  - EXEC_DIR=$HOME/bin
